# Generated by Django 5.2.5 on 2026-07-18 13:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "deployment_mode",
                    models.CharField(
                        choices=[
                            ("CLOUD", "Felhő"),
                            ("ON_PREMISES", "On-premises"),
                            ("HYBRID", "Hibrid"),
                        ],
                        max_length=20,
                    ),
                ),
                ("concurrent", models.BooleanField(default=False)),
                (
                    "concurrent_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("SUBSCRIPTION", "Előfizetés"),
                            ("PERPETUAL", "Örökös"),
                            ("TRIAL", "Próba"),
                            ("OTHER", "Egyéb"),
                        ],
                        max_length=20,
                    ),
                ),
                ("secret_reference", models.TextField(blank=True)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("expires_at", models.DateField(blank=True, db_index=True, null=True)),
                ("auto_renews", models.BooleanField(default=False)),
                ("notification_intervals", models.JSONField(blank=True, default=list)),
                ("notification_emails", models.JSONField(blank=True, default=list)),
                (
                    "cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("currency", models.CharField(default="HUF", max_length=3)),
                ("cost_center", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Aktív"),
                            ("EXPIRING", "Lejáró"),
                            ("EXPIRED", "Lejárt"),
                            ("TERMINATED", "Megszüntetett"),
                            ("ARCHIVED", "Archivált"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="licenses_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notification_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="license_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_licenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="licenses_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "permissions": [
                    ("export_license", "Can export licenses"),
                    ("archive_license", "Can archive licenses"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LicenseDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file", models.FileField(upload_to="licenses/%Y/%m/")),
                ("original_name", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="licenses.license",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[("MANUFACTURER", "Gyártó"), ("DISTRIBUTOR", "Disztribútor")],
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(fields=("name", "kind"), name="unique_party_kind")
                ],
            },
        ),
        migrations.AddField(
            model_name="license",
            name="distributor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"kind": "DISTRIBUTOR"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="distributed_licenses",
                to="licenses.party",
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"kind": "MANUFACTURER"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="manufactured_licenses",
                to="licenses.party",
            ),
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("interval_days", models.PositiveIntegerField()),
                ("recipients", models.JSONField(default=list)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="licenses.license",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("license", "interval_days"),
                        name="unique_license_interval_notification",
                    )
                ],
            },
        ),
    ]
