# Generated by Django 5.2.5 on 2026-07-18 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="party",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name="PartyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("position", models.CharField(blank=True, max_length=100)),
                ("active", models.BooleanField(default=True)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="licenses.party",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
