# Generated by Django 5.2.5 on 2026-07-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0002_party_address_party_postal_code_partycontact"),
    ]

    operations = [
        migrations.AddField(
            model_name="licensedocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("LICENSE_FILE", "Licencfájl"),
                    ("CONTRACT", "Szerződés"),
                    ("INVOICE", "Számla"),
                    ("INSTALLATION_GUIDE", "Telepítési útmutató"),
                    ("OTHER", "Egyéb"),
                ],
                default="OTHER",
                max_length=30,
            ),
        ),
    ]
