# Generated by Django 5.2.5 on 2026-07-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IntegrationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("singleton", models.BooleanField(default=True, editable=False, unique=True)),
                ("ldap_enabled", models.BooleanField(default=False)),
                ("ldap_server_uri", models.CharField(blank=True, max_length=255)),
                ("ldap_use_ssl", models.BooleanField(default=True)),
                ("ldap_base_dn", models.CharField(blank=True, max_length=255)),
                ("ldap_bind_dn", models.CharField(blank=True, max_length=255)),
                ("ldap_bind_password", models.TextField(blank=True)),
                (
                    "ldap_user_filter",
                    models.CharField(default="(sAMAccountName={username})", max_length=255),
                ),
                ("ldap_admin_group", models.CharField(blank=True, max_length=255)),
                ("ldap_manager_group", models.CharField(blank=True, max_length=255)),
                ("ldap_reader_group", models.CharField(blank=True, max_length=255)),
                ("smtp_host", models.CharField(blank=True, max_length=255)),
                ("smtp_port", models.PositiveIntegerField(default=587)),
                ("smtp_use_tls", models.BooleanField(default=True)),
                ("smtp_username", models.CharField(blank=True, max_length=255)),
                ("smtp_password", models.TextField(blank=True)),
                ("smtp_from_email", models.EmailField(blank=True, max_length=254)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
