# Generated by Django 5.2.5 on 2026-07-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationsettings",
            name="backup_destination",
            field=models.CharField(
                choices=[
                    ("LOCAL", "Helyi tárhely"),
                    ("S3", "Amazon S3"),
                    ("AZURE", "Azure Blob Storage"),
                    ("SHAREPOINT", "Microsoft SharePoint"),
                ],
                default="LOCAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="backup_interval_hours",
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="backup_local_subdirectory",
            field=models.CharField(default="full", max_length=100),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="backup_remote_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="backup_retention_days",
            field=models.PositiveIntegerField(default=14),
        ),
    ]
