# Generated by Django 5.2.5 on 2026-07-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_integrationsettings_backup_destination_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationsettings",
            name="backup_smb_domain",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="backup_smb_host",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="backup_smb_password",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="backup_smb_port",
            field=models.PositiveIntegerField(default=445),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="backup_smb_share",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="backup_smb_subdirectory",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="backup_smb_username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="network_address",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="network_dhcp",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="network_dns_primary",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="network_dns_secondary",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="network_gateway",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="network_hostname",
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="network_interface",
            field=models.CharField(default="ens18", max_length=50),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="network_public_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="network_search_domain",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="integrationsettings",
            name="backup_destination",
            field=models.CharField(
                choices=[
                    ("LOCAL", "Helyi tárhely"),
                    ("S3", "Amazon S3"),
                    ("AZURE", "Azure Blob Storage"),
                    ("SHAREPOINT", "Microsoft SharePoint"),
                    ("SMB", "SMB hálózati megosztás"),
                ],
                default="LOCAL",
                max_length=20,
            ),
        ),
    ]
