# Generated by Django 5.2.5 on 2026-07-18 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("singleton", models.BooleanField(default=True, editable=False, unique=True)),
                ("company_name", models.CharField(max_length=200)),
                ("company_short_name", models.CharField(max_length=50)),
                ("country", models.CharField(default="HU", max_length=2)),
                ("timezone", models.CharField(default="Europe/Budapest", max_length=64)),
                ("language", models.CharField(default="hu", max_length=10)),
                ("support_email", models.EmailField(max_length=254)),
                ("support_phone", models.CharField(blank=True, max_length=40)),
                ("setup_completed", models.BooleanField(default=False)),
                ("installation_date", models.DateTimeField(blank=True, null=True)),
                ("application_version", models.CharField(default="1.0-dev0", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "first_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
